### ISSUE TITLE
APNS Push not available in Australia?

### ISSUE THREAD

**Issue by huwr** [kaunteya/APNSwift#2]
Seems that the app store listing for APNS Push is not available in the Australian App Store. Is this for any particular reason? 
![Screen Shot 2019-11-03 at 10 33 36](https://user-images.githubusercontent.com/790199/68078207-6ac43780-fe25-11e9-8450-1ecabc0a6ce8.png)

**Comment by kaunteya** [comment]
This app has been taken down from the App store
